# Generated by Django 5.2 on 2025-04-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзины", "verbose_name_plural": "Корзины"},
        ),
    ]
