# Generated by Django 5.2 on 2025-04-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_alter_cart_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
    ]
