# Generated by Django 5.1.7 on 2025-03-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rooms', models.CharField(blank=True, max_length=20, null=True)),
                ('square', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('commission', models.CharField(blank=True, max_length=20, null=True)),
                ('deposit', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
