# Generated by Django 5.2 on 2025-04-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="delivery_adress",
            new_name="delivery_address",
        ),
    ]
